export const styles = {
  tagDivStyle: {
    marginTop: "30px",
    padding: "0",
    display: "flex",
    flexWrap: "wrap" as "wrap",
    border: "1px solid #f0f5ff",
    alignItems: "center",
  },
  buttonStyle: {
    backgroundColor: "#f0f5ff",
    height: "40px",
    color: "#616fc8",
    width: "100px",
    outline: "none",
    border: "1px solid #616fc8",
    cursor: "pointer",
  },
  buttonStyleForAddTodo: {
    marginTop: "30px",
    backgroundColor: "#f0f5ff",
    height: "40px",
    color: "#616fc8",
    width: "100px",
    outline: "none",
    border: "1px solid #616fc8",
    cursor: "pointer",
  },
  buttonStyleForAddTodoBack: {
    marginTop: "30px",
    marginLeft: "20px",
    backgroundColor: "white",
    height: "40px",
    color: "red",
    width: "100px",
    outline: "none",
    border: "1px solid red",
    cursor: "pointer",
  },
  labelStyle: {
    height: "34px",
    width: "130px",
    padding: "10px",
    fontSize: "22px",
    border: "1px solid #616fc8",
    color: "#616fc8",
    backgroundColor: "#f0f5ff",
  },
  inputStyle: {
    height: "50px",
    width: "100%",
    fontSize: "20px",
    padding: "0 10px",
    outline: "none",
  },
  inputStyleDashboard: {
    height: "38px",
    padding: "0 10px",
    border: "none",
    outline: "1px solid #616fc8",
  },
  tagUlStyle: {
    padding: "0",
    listStyleType: "none",
    display: "flex",
    flexWrap: "wrap" as "wrap",
  },
  tagLiStyle: { padding: "10px", margin: "10px", backgroundColor: "#f0f5ff" },
  tagInput: {
    padding: "0 10px",
    height: "50px",
    outline: "none",
    border: "none",
    fontSize: "15px",
  },
};
